@echo off
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
start mspaint 
start notepad
start write 
start cmd
start explorer
start control
start calc
start mspaint 
start notepad
start write
